import dotenv from "dotenv";
import { z } from "zod";

dotenv.config();

const schema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  CORE_PORT: z.coerce.number().default(3000),
  CORE_HOST: z.string().default("0.0.0.0"),
  AUTH_ISSUER: z.string().default("http://localhost:3000"),
  API_BASE_URL: z.string().default("http://localhost:3000"),
  UI_BASE_URL: z.string().default("http://localhost:3001"),
  VERIFY_BASE_URL: z.string().default("http://localhost:3000"),
  RP_ID: z.string().default("localhost"),
  EXPECTED_ORIGIN: z.string().default("http://localhost:3000"),
  SESSION_COOKIE_SECURE: z.string().default("false"),
  SESSION_TTL_SECONDS: z.coerce.number().default(60 * 60 * 8),
  AUTH_REQUEST_TTL_SECONDS: z.coerce.number().default(15 * 60),
  AUTH_DISABLE_SSO: z.string().default("true"),
  TENANT_SALT: z.string().default("dev-salt"),
  POSTGRES_DB: z.string().default("zauth"),
  POSTGRES_USER: z.string().default("zauth"),
  POSTGRES_PASSWORD: z.string().default("zauth"),
  POSTGRES_HOST: z.string().default("localhost"),
  POSTGRES_PORT: z.coerce.number().default(5432),
  REDIS_URL: z.string().default("redis://localhost:6379"),
  DEMO_CLIENT_ID: z.string().default("demo-web-client"),
  DEMO_REDIRECT_URI: z.string().default("http://localhost:3001/callback"),
  NOTES_CLIENT_ID: z.string().default("notes-web-client"),
  NOTES_REDIRECT_URI: z.string().default("http://localhost:3002/callback"),
  LIVENESS_MODE: z.enum(["mock", "challenge"]).default("challenge"),
  LIVENESS_MIN_CONFIDENCE: z.coerce.number().default(0.72),
  PRAMAAN_V2_ENABLED: z.string().default("true"),
  AUTH_REQUIRE_ZK_FOR_LOGIN: z.string().default("false"),
  ZK_VERIFIER_MODE: z.enum(["mock", "real"]).default("mock"),
  ZK_CIRCUIT_ID: z.string().default("biometric_commitment_v1"),
  ZK_VERIFY_KEY_PATH: z.string().default("zk/verification_key.json"),
  ZK_REQUIRE_CHALLENGE_BINDING: z.string().default("true"),
  ANCHOR_ENABLED: z.string().default("false"),
  ANCHOR_INTERVAL_HOURS: z.coerce.number().default(24),
  ANCHOR_CHAIN_RPC_URL: z.string().optional(),
  ANCHOR_CHAIN_CONTRACT: z.string().optional(),
  ANCHOR_PRIVATE_KEY: z.string().optional(),
  ANCHOR_IPFS_API: z.string().optional(),
  ANCHOR_PINATA_JWT: z.string().optional(),
  LOG_LEVEL: z.enum(["debug", "info", "warn", "error"]).default("info")
});

const env = schema.parse(process.env);

export const config = {
  nodeEnv: env.NODE_ENV,
  isProd: env.NODE_ENV === "production",
  corePort: env.CORE_PORT,
  coreHost: env.CORE_HOST,
  issuer: env.AUTH_ISSUER,
  apiBaseUrl: env.API_BASE_URL,
  uiBaseUrl: env.UI_BASE_URL,
  verifyBaseUrl: env.VERIFY_BASE_URL,
  rpId: env.RP_ID,
  expectedOrigin: env.EXPECTED_ORIGIN,
  sessionCookieSecure: env.SESSION_COOKIE_SECURE === "true",
  sessionTtlSeconds: env.SESSION_TTL_SECONDS,
  authRequestTtlSeconds: env.AUTH_REQUEST_TTL_SECONDS,
  authDisableSso: env.AUTH_DISABLE_SSO === "true",
  tenantSalt: env.TENANT_SALT,
  postgres: {
    database: env.POSTGRES_DB,
    user: env.POSTGRES_USER,
    password: env.POSTGRES_PASSWORD,
    host: env.POSTGRES_HOST,
    port: env.POSTGRES_PORT
  },
  redisUrl: env.REDIS_URL,
  demoClientId: env.DEMO_CLIENT_ID,
  demoRedirectUri: env.DEMO_REDIRECT_URI,
  notesClientId: env.NOTES_CLIENT_ID,
  notesRedirectUri: env.NOTES_REDIRECT_URI,
  livenessMode: env.LIVENESS_MODE,
  livenessMinConfidence: env.LIVENESS_MIN_CONFIDENCE,
  pramaanV2Enabled: env.PRAMAAN_V2_ENABLED === "true",
  authRequireZkForLogin: env.AUTH_REQUIRE_ZK_FOR_LOGIN === "true",
  zkVerifierMode: env.ZK_VERIFIER_MODE,
  zkCircuitId: env.ZK_CIRCUIT_ID,
  zkVerifyKeyPath: env.ZK_VERIFY_KEY_PATH,
  zkRequireChallengeBinding: env.ZK_REQUIRE_CHALLENGE_BINDING === "true",
  anchorEnabled: env.ANCHOR_ENABLED === "true",
  anchorIntervalHours: env.ANCHOR_INTERVAL_HOURS,
  anchorChainRpcUrl: env.ANCHOR_CHAIN_RPC_URL,
  anchorChainContract: env.ANCHOR_CHAIN_CONTRACT,
  anchorPrivateKey: env.ANCHOR_PRIVATE_KEY,
  anchorIpfsApi: env.ANCHOR_IPFS_API,
  anchorPinataJwt: env.ANCHOR_PINATA_JWT,
  logLevel: env.LOG_LEVEL
} as const;
